services:
  mongodb:
    image: mongo:8.0
    container_name: crud-users-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crud_users
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
